### ISSUE TITLE
Create AddEvent page.

### ISSUE THREAD

**Issue by iserifith** [kemamanwebtech/ajakk#19]
Should have input fields for all required properties (name, desc, location, time, type...etc see database schema table EVENT for details)

This class should be a modal and will be called by a button **ADD EVENT** from homepage.

**Comment by mrafsyam** [comment]
Should include a **date picker** and a **textbox for time.**

Both will be combine to be the data for **CONFIRMED_DATE** field as you see in the table below.

Also, we need to add another column **SPORTS_TYPE**  in the table **EVENT**;
Possible values for this later would be "basketball, soccer, futsal, badminton" etc.

Please add this change.

![screenshot from 2017-04-13 00-11-37](https://cloud.githubusercontent.com/assets/6120781/24967781/cf9dd266-1fdd-11e7-8db9-4571ad5d9a4b.png)

**Comment by mrafsyam** [comment]
done.
