### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by mrafsyam** [kemamanwebtech/ajakk#2]
- [ ] Create database named "ajakk" at KWT server.

- [ ] Create tables using schema creation scripts in /trunk/database/schema. Just run it on the KWT's mysql. Currently, we have 4 tables to create.

![screenshot from 2017-03-05 11-15-30](https://cloud.githubusercontent.com/assets/6120781/23584204/1ea71afa-0195-11e7-9d05-9019ba6282f5.png)

**Comment by mrafsyam** [comment]
@iserifith  Make sure to update svn `svn update` to get the latest version + new scripts

**Comment by iserifith** [comment]
@mrafsyam done
