### ISSUE TITLE
create DAO and DTO classes

### ISSUE THREAD

**Issue by mrafsyam** [kemamanwebtech/ajakk#4]
More info on DAO pattern : https://www.tutorialspoint.com/design_pattern/data_access_object_pattern.htm

**DAO for User. Name : userDAO.java**
- create User   (INSERT INTO....)
- delete User   (DELETE FROM...)
- update User  (UPDATE..)
- get list of Users (SELECT...)
use DTO for user : UserDTO.java

**DAO for Event. Name : eventDAO.java**
- create Event
- delete Event
- update Event
- get list of Events
use DTO for event : EventDTO.java

**Note**
All DAOs should be called from FactoryDAO.java
All DAOs share same connection using getConnection() function in FactoryDAO. 
Once a DAO is created, make sure there is a function to specifically return that DAO you have created i.e. getEventDAO()
Take a look at LoginDAO.java and LoginDTO.java (this have been implemented)

**Comment by iserifith** [comment]
@mrafsyam done

**Comment by mrafsyam** [comment]
Done. Specific issue will be opened if need rework.
