### ISSUE TITLE
Create scheme for Venue and DTO and DAO classes for that

### ISSUE THREAD

**Issue by iserifith** [kemamanwebtech/ajakk#7]
1. Create schema creation script for :  create table venue

- venue_id
- owner_name
- owner_hp
- payment_details
- venue_rate
- location
- loc_gps
- loc_address
- venue_photo
- venue_des

2. Create DTO class for Venue : VenueDTO

3. Create DAO class for Venue : VenueDAO

**Comment by mrafsyam** [comment]
Can you add these 2 to the schema script 

1. Header : 
I.e. -- ------------------------------------------------------------------------
-- Abstract:     ajakk: create table AJAKK_PASS
...
...

2. Add insert dummy query at the bottom of the script

**Comment by mrafsyam** [comment]
Done. Will make use some of the output later in a new issue.
